-- 商品分类表
CREATE TABLE IF NOT EXISTS product_category (
    id BIGINT PRIMARY KEY COMMENT '分类ID',
    parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父分类ID，0为顶级',
    name VARCHAR(50) NOT NULL COMMENT '分类名称',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    icon VARCHAR(255) DEFAULT NULL COMMENT '图标',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0-禁用 1-启用',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品分类表';

-- 商品SPU表
CREATE TABLE IF NOT EXISTS product_spu (
    id BIGINT PRIMARY KEY COMMENT 'SPU ID',
    category_id BIGINT NOT NULL COMMENT '分类ID',
    name VARCHAR(100) NOT NULL COMMENT '商品名称',
    description TEXT DEFAULT NULL COMMENT '商品描述',
    brand VARCHAR(50) DEFAULT NULL COMMENT '品牌',
    main_image VARCHAR(255) DEFAULT NULL COMMENT '主图URL',
    images TEXT DEFAULT NULL COMMENT '商品图片列表(JSON)',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0-下架 1-上架',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_category_id (category_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品SPU表';

-- 商品SKU表
CREATE TABLE IF NOT EXISTS product_sku (
    id BIGINT PRIMARY KEY COMMENT 'SKU ID',
    spu_id BIGINT NOT NULL COMMENT '所属SPU ID',
    name VARCHAR(200) NOT NULL COMMENT 'SKU名称',
    sku_code VARCHAR(100) DEFAULT NULL COMMENT 'SKU编码',
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '价格',
    stock INT NOT NULL DEFAULT 0 COMMENT '库存',
    images VARCHAR(255) DEFAULT NULL COMMENT 'SKU图片',
    specs TEXT DEFAULT NULL COMMENT '规格参数(JSON)',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0-禁用 1-启用',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_spu_id (spu_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品SKU表';
